version: 2.1
orbs:
  node: circleci/node:1.1.6
jobs:
  build:
    docker:
      image: circleci/node:1.1.6
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      image: circleci/node:1.1.6
    steps:
      - checkout
      - run: echo "Testing stuff"
      - run: npm install
      - run: npm test
  hithere:
    docker:
      image: circleci/node:1.1.6
    steps:
      - checkout
      - run: echo "Hi there!"
workflows:
    build-test_and_lint:
      jobs:
        - build
        - hithere
        - test:
           requires:
             - hithere