version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test_1:
    executor:
      name: node/default
    steps:
      - checkout
      - run: echo "A first hello"
  build-and-test_2:
    executor:
      name: node/default
    steps:
      - checkout
      - run: echo "A second hello"
workflows:
    build-and-test_workflow:
      jobs:
        - build-and-test_1
        - build-and-test_2